# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a93cd8ebec329d694224f4269b936ef69e77b58e4fc2f946cbab031323b8bd72c57e243fcad95d2515ca88256d0117ac3bd1f159d50f6f0466782a4240d619

test:
  secret_key_base: b9b93d022ed3e29cced311482209a505b83a5ed05bfc03d5824c19ae6f782c5bee2112ed241d20051ab27361f33d4384a9979d49da3728e2f5f00769fa6f324a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
